services:
  - type: web
    name: ai-resume-shortlister
    env: python
    plan: free
    runtime: python-3.12.6
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
